describe('Flowchart Image Import Feature', () => {
  beforeEach(() => {
    // Visit the page where FlowchartBuilder is rendered.
    // Assuming it's the root page or a specific route.
    // Adjust if necessary.
    cy.visit('/');
  });

  it('should allow image upload, render flowchart, and display validation report', () => {
    // 1. Define Mock API Response
    const mockChartJson = {
      nodes: [
        { id: 'node_1', type: 'process', position: { x: 50, y: 50 }, data: { label: 'Process 1' } },
        { id: 'node_2', type: 'decision', position: { x: 50, y: 150 }, data: { label: 'Is it valid?' } },
        // Missing a start node and an end node to trigger validation errors
        // node_3 is an orphan if we add an edge to it from a non-existent node or no edges to it
        { id: 'node_3', type: 'process', position: { x: 200, y: 150 }, data: { label: 'Orphan Process' } },
      ],
      edges: [
        // Edge from node_2 to node_3, but node_1 is an orphan source if used in an edge
        { id: 'edge_1', source: 'node_2', target: 'node_3', type: 'yes' }
      ],
    };

    const mockApiResponse = {
      chartJson: mockChartJson,
      // Validation report is generated by frontend, so backend only sends chartJson
    };

    // 2. Intercept the API call
    cy.intercept('POST', '/api/analyze_flowchart_image', {
      statusCode: 200,
      body: mockApiResponse,
    }).as('analyzeImageCall');

    // 3. Simulate File Upload
    // The actual file input is hidden and managed by the useImportFlowchart hook.
    // The hook creates an input element on the fly.
    // Cypress doesn't easily interact with dynamically created, short-lived hidden inputs.
    // A common workaround is to have a visible input for testing or to directly trigger the hook's file handler.
    // Since the hook's `triggerImport` dynamically creates an input, we need a way to target it.
    //
    // Alternative: If FlowchartBuilder had a data-testid on its root, we could potentially
    // attach the file to a more generic drop area if one existed, or use a plugin for hidden inputs.
    //
    // For now, let's assume the "Import" button is the primary interaction point.
    // We need to ensure that when this button is clicked, the dynamically created input
    // can be targeted by Cypress if it needs to attach a file.
    //
    // A more robust way for Cypress is usually to have a persistent, though perhaps visually hidden,
    // input element that Cypress can get a handle on and use .selectFile()
    //
    // Given the current hook implementation (`input.click()`), direct file attachment is tricky.
    // Let's check if the `FlowchartBuilder.tsx` has the `data-testid="flowchart-image-upload-input"`
    // on the input it *used* to have. If the hook re-creates an input without a stable selector, this is hard.

    // The hook creates an input like:
    // const input = document.createElement('input'); input.type = 'file'; input.click();
    // This input is never added to the DOM permanently for Cypress to grab before it's clicked.
    //
    // The most robust way to test file uploads with such dynamic inputs is often to
    // directly manipulate the component's state or props if possible, or to ensure
    // the dynamically created input gets a predictable ID or data-testid IF it's briefly in DOM.
    // Or, stub the part of the hook that creates the input and handles the file.
    //
    // For this E2E, we'll focus on the "Import" button existing and the interception.
    // The `cy.fixture` and `selectFile` are for when you have an actual input field.

    cy.get('button[title="Upload Flowchart Image"]').should('be.visible').as('importButton');
    // At this point, clicking @importButton would trigger the dynamic input.
    // To make this testable without complex input finding, we'd ideally modify the hook
    // or component to use a fixed, hidden input.
    //
    // Workaround: Since the API call is what we want to test the reaction to,
    // and the file selection itself is hard to script against the dynamic input,
    // we can test the UI update *after* the API call is expected to complete.
    // We can't use `cy.get('input[type="file"]').selectFile(...)` if the input is created and clicked by JS internally.

    // Simplification for this test: Assume the file selection *would* happen.
    // We trigger the process by clicking the button, then wait for the mocked API call.
    cy.get('@importButton').click();

    cy.wait('@analyzeImageCall').its('response.statusCode').should('eq', 200);

    // 4. Verify Flowchart Rendering
    cy.get(`[key="${mockChartJson.nodes[0].id}"]`).should('contain', mockChartJson.nodes[0].data.label);
    cy.get(`[key="${mockChartJson.nodes[1].id}"]`).should('contain', mockChartJson.nodes[1].data.label);
    cy.get(`[key="${mockChartJson.nodes[2].id}"]`).should('contain', mockChartJson.nodes[2].data.label);

    // Verify edge rendering (more complex, depends on SVG structure)
    // For now, just check if an SVG element exists with lines/markers, assuming edges are drawn.
    cy.get('svg line[marker-end="url(#arrowhead)"]').should('have.length.at.least', mockChartJson.edges.length);

    // 5. Verify Validation Report Display
    // Expected errors based on mockChartJson and validator.js logic:
    // - No Start block
    // - No End block
    // - Node 1 (process) is missing next connection (because it's an orphan)
    // - Node 2 (decision) might be missing a false path if only 'yes' edge is defined.
    //   (Our mock edge is 'yes'. Validator expects trueBlock and falseBlock for decisions)
    // - Node 3 (orphan process) might be unreachable if node_1 is chosen as implicit start by validator.
    //
    // The transformFlowchartDataForValidation will convert nodes/edges to blocks.
    // node_1: type Process, no outgoing edges -> "missing its next connection"
    // node_2: type Decision, one 'yes' edge to node_3 -> "missing its False path connection"
    // node_3: type Process, no outgoing edges -> "missing its next connection"
    // General: No Start block, No End block.

    const expectedValidationMessages = [
      "No Start block defined for the flowchart.", // Or "The flowchart must contain at least one 'Start' block."
      "The flowchart must contain at least one 'End' block.",
      `Block "${mockChartJson.nodes[0].id}" is missing its "next" connection.`, // Process 1
      `Decision block "${mockChartJson.nodes[1].id}" is missing its False path connection.`, // Is it valid?
      `Block "${mockChartJson.nodes[2].id}" is missing its "next" connection.`, // Orphan Process
      // Might also have unreachability errors depending on how validator processes without startBlockId
    ];

    cy.get('.bg-yellow-50').should('be.visible').within(() => {
      cy.get('h5').should('contain', 'Image Import Validation Issues:');
      const reportItems = cy.get('ul li');
      reportItems.should('have.length.gte', 3); // Expecting at least a few errors

      expectedValidationMessages.forEach(msg => {
        // Allow partial match for messages that might have slight variations
        // (e.g. "No Start block defined" vs "must contain at least one 'Start' block")
        if (msg.includes("Start block")) {
            reportItems.contains(/Start block/i).should('exist');
        } else {
            reportItems.should('contain.text', msg.substring(0, 50)); // Check a substring for robustness
        }
      });
    });

    // 6. Verify Node Highlighting
    // Nodes 0, 1, 2 should be highlighted as they have errors associated.
    cy.get(`[key="${mockChartJson.nodes[0].id}"]`).should('have.class', 'border-red-500');
    cy.get(`[key="${mockChartJson.nodes[1].id}"]`).should('have.class', 'border-red-500');
    cy.get(`[key="${mockChartJson.nodes[2].id}"]`).should('have.class', 'border-red-500');

    // Clear the report and check if it disappears
    cy.get('.bg-yellow-50 button:contains("Dismiss Report")').click();
    cy.get('.bg-yellow-50').should('not.exist');
  });

  it('should display an error message if the image analysis API fails', () => {
    // Intercept the API call to simulate a server error
    cy.intercept('POST', '/api/analyze_flowchart_image', {
      statusCode: 500,
      body: { detail: 'Internal Server Error during analysis' },
    }).as('analyzeImageCallError');

    // Trigger the import
    cy.get('button[title="Upload Flowchart Image"]').click();
    cy.wait('@analyzeImageCallError');

    // Verify error message display
    cy.get('.bg-red-100').should('be.visible').within(() => {
      cy.get('strong').should('contain', 'Import Error:');
      cy.contains('Internal Server Error during analysis').should('be.visible');
    });

    // Clear the error and check
    cy.get('.bg-red-100 button:contains("Dismiss")').click();
    cy.get('.bg-red-100').should('not.exist');
  });
});
